### ISSUE TITLE
 acc new コマンドがエラーになる

### ISSUE THREAD

**Issue by taigok** [TaigoKuriyama/atcoder#5]
```sh
$ acc new abc162
abc162/contest.acc.json created.
create project of AtCoder Beginner Contest 162
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/taigokuriyama/.local/bin/oj ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by taigok** [comment]
[macOS Catalina にしたら、Anaconda 使えなくなった場合の対処法](https://qiita.com/akinko/items/1909c8d0145d9ba530b9) の通りにまず行い、Anaconca を使えるようにした。

**Comment by taigok** [comment]
シバンを変更。

```sh
$ vim /Users/taigokuriyama/.local/bin/oj
```

```sh
#!/Users/taigokuriyama/anaconda3/bin/python
```
